version: '3'

services:
  postgres:
    container_name: 'chat_postgres'
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/data/postgresql
    restart: always
    env_file:
      - .env

volumes:
  postgres-data:
